[pytest]
DJANGO_SETTINGS_MODULE = greentalk.settings.local
python_files = tests/*/test_*.py tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --cov=apps
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=70
    -v
